### PR TITLE
remove all flatpak stuff, because it will be hosted directly on flathub

### PR DESCRIPTION
**Pull request by Murmele**
- [x] URL in the readme is updated

### CODE REVIEW

**Comment by chipmuenk** [comment]
The license depends on the mode of distribution (as described in the "License" tab of pyfda:

> 

> The pyFDA source code is published under a permissive MIT license at the Github repository [chipmuenk/pyfda](https://github.com/chipmuenk/pyfda) and at [PyPI](https://pypi.org/project/pyfda/), Icons (except the pyFDA icon itself) are taken from the ["Open Iconic"](https://useiconic.com/open/) collection (MIT license).
> The self-contained pyFDA package (bundled e.g. with the help of pyInstaller or as a flatpak) is published under a GPLv3 license as it bundles some components with (L)GPL licenses, requiring an [(L)GPL compliant license](https://velovix.github.io/post/lgpl-gpl-license-compliance-with-pyinstaller/). See also [wikipedia](https://en.wikipedia.org/wiki/License_compatibility) on license compatibility.

For this reason, I think pyfda needs to be distributed under the GPLv3 license at Flathub.

**Comment by Murmele** [comment]
ok than I will change to it

**Comment by Murmele** [comment]
@chipmuenk 
I added a flatpak build manifest adapted from Gittyup, not sure if it will be executed when it is available the first time

**Comment by chipmuenk** [comment]
Looks good! I'd just like to change "pyFDA" in favour of "pyfda" because the capitalized spelling has given me trouble several times in the past when exchanging files between Windows and Linux.

**Comment by chipmuenk** [comment]
@Murmele If changing the case from "pyFDA" to "pyfda" creates extra work just tell me, then I'll merge your PR the way it is.

**Comment by Murmele** [comment]
> 

No thats not a problem I will do

**Review by chipmuenk — APPROVED** [review]
Looks good to me, it's a good idea to put all flatpak related stuff on flathub

**Comment by chipmuenk** [comment]
@Murmele : CI still fails at the moment (should it be working already?) with the followig error

```
2022-04-08T14:34:45.0251564Z From https://github.com/chipmuenk/pyfda
2022-04-08T14:34:45.0253158Z  * [new ref]         a2be5eaabd182e223ba8e940390bebc4bf1b22f8 -> origin/master
2022-04-08T14:34:45.0279483Z ##[endgroup]
2022-04-08T14:34:45.0280224Z ##[group]Determining the checkout info
2022-04-08T14:34:45.0287412Z ##[endgroup]
2022-04-08T14:34:45.0299141Z ##[group]Checking out the ref
2022-04-08T14:34:45.0300307Z [command]/usr/bin/git checkout --progress --force -B master refs/remotes/origin/master
2022-04-08T14:34:45.1328532Z Reset branch 'master'
2022-04-08T14:34:45.1333172Z branch 'master' set up to track 'origin/master'.
2022-04-08T14:34:45.1369917Z ##[endgroup]
2022-04-08T14:34:45.1446617Z [command]/usr/bin/git log -1 --format='%H'
2022-04-08T14:34:45.1471324Z 'a2be5eaabd182e223ba8e940390bebc4bf1b22f8'
2022-04-08T14:34:45.1808165Z ##[group]Run GuillaumeFalourd/clone-github-repo-action@v1
2022-04-08T14:34:45.1808497Z with:
2022-04-08T14:34:45.1808722Z   owner: flathub
2022-04-08T14:34:45.1809285Z   repository: com.github.chipmuenk.pyfda
2022-04-08T14:34:45.1809567Z ##[endgroup]
2022-04-08T14:34:45.2029849Z ##[command]/usr/bin/docker run --name bcf09854093cf25d94ed1b05322187b56d20e_812943 --label 2bcf09 --workdir /github/workspace --rm -e INPUT_OWNER -e INPUT_REPOSITORY -e INPUT_ACCESS-TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --network github_network_3c4cab989daa41768fc0556b2cf3f56c -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/pyfda/pyfda":"/github/workspace" 2bcf09:854093cf25d94ed1b05322187b56d20e  "flathub" "com.github.chipmuenk.pyfda" ""
2022-04-08T14:34:45.6220138Z Cloning into 'com.github.chipmuenk.pyfda'...
2022-04-08T14:34:45.9234476Z fatal: could not read Username for 'https://github.com': No such device or address
2022-04-08T14:34:45.9276783Z Error: Couldn't clone com.github.chipmuenk.pyfda repository. Check the inputs or the PAT scope.
```

**Comment by Murmele** [comment]
@chipmuenk No not yet, the problem is that flathub/com.github.chipmuenk.pyfda does not exist yet, it will be created as soon as the pullrequest on flathub will be processed. I will create a new pullrequest with the CI build after it is uploaded at flathub

**Pull request merged**
