### PR TITLE
[WIP] start of pyqt5 compatibility.

### PR DESCRIPTION
**Pull request by cfelton**
This commit contains the start of PyQt5 compatibility, this allows
the pyfda pyqt application to work with PyQt4 or PyQt5.

This merge request is **NOT COMPLETE**.  Need to finish the pyqt5 compatibility integration.

### CODE REVIEW

**Comment by chipmuenk** [comment]
Ok, waiting with the merge till you tell me.

**Comment by chipmuenk** [comment]
Could you make another pull request against my branch "pyqt5"? Then I can play around with your changes without affecting master.

**Comment by cfelton** [comment]
@chipmuenk it looks like you merged my branch into your branch?  Let me know if you need anything else.  I have not upgraded / ported pyqt4 to pyqt5 before.  Not sure what the best practices are for supporting both.

**Comment by chipmuenk** [comment]
Yeah, I created a branch under the same name pyqt5 and merged your branch into it. I need to have a installable version of pyfda by the end of next week, so I thought I'd take over the search & replace slave job ... The input_widgets files are working under pyqt5 now, I'll tackle the rest of the files during the weekend. I'll push the current state now, but I think it would be more effective if I finished the job.

Thanks once more for pointing me in the right direction, using a central compat.py file.

I think the spyder guys have taken a similiar road by creating the qtpy (nice name :-)  module but I didn't want to add another dependency.

**Comment by chipmuenk** [comment]
I think pyFDA should be compatible with pyqt5 now. Not quite sure though, because my Anaconda Qt5 environment seems to fall back to Qt4 when something is missing. If your system is pyQt5 only, it would be great if you could do a test run. I've uploaded the update to pip; if everything runs fine I'll upload it to the Anaconda cloud as well.

**Pull request merged**
