### PR TITLE
change version in appdata and fix flatpak CI

### PR DESCRIPTION
**Pull request by Murmele**

### CODE REVIEW

**Review by chipmuenk — COMMENTED** [review]
Looks good, but what does the version number refer to? Current pyfda version is 0.6.1.

**Comment by Murmele** [comment]
> 

I don't know what I did there sorry. I added now 0.6.1 and 0.6.0

**Comment by Murmele** [comment]
This is how it looks on flathub:
grafik
seems that nested <b> and <ul> do not work properly (appdata.xml)

**Comment by Murmele** [comment]
@chipmuenk

**Review by chipmuenk — APPROVED** [review]
Looks good, thanks for updating!

**Pull request merged**
