### PR TITLE
New Status Window

### PR DESCRIPTION
**Pull request by sp1nelson**
Add new status window to main display.  Display errors here as well as in log file, terminal window.
Add basic input error checking on amplitude, frequencies.
Add dynamic checkBoxes for future work on IIR elliptical filter

### CODE REVIEW

**Comment by chipmuenk** [comment]
@sp1nelson : I tested your branch locally, works nicely both under Py2 and Py3! I think it is very helpful not having to stare at the console window with one eye all the time.

There is just one small and one major grief:
- Minor grief: I am using pyFDA for lectures with a beamer and trying to optimize the UI for a compromise between minimum footprint and readability. For my taste, the logging window takes up too much space with its two splitters and title bar. Could you perhaps comment out one splitter and the title bar for the time being? Then we can discuss / try other options later, e.g. adding a label / title to the logging window

- Major grief: I think the PR is too large, containing two separate topics (logger and zero-phase elliptical filter). I propose splitting the PR and also creating a new filter class like "ellip_linphase" as it seems you are still working on the actual filter implementation. Then we can comment out your implementation in "filter_list.txt" until it is finished.

What do you think?

**Comment by chipmuenk** [comment]
I just noticed you also did some work on parameter checking for amplitude / frequency specs as well as some cleaning up of logging messages. Nice!

**Comment by chipmuenk** [comment]
I've done a lot of cherry picking in git and integrated all your commits into master except 4d8e043  ("	Add dynamic checkBoxes for later use "). 

Some finetuning on the logging window is required but I think you've found an elegant solution to reroute all the logging messages. Neat!

**Comment by sp1nelson** [comment]
Yes, I like your ideas...I will work on it and update my branch, then a
pull request later...

**Pull request closed without merging**
