### PR TITLE
Flatpak package

### PR DESCRIPTION
**Pull request by Murmele**
Manifest to create a flatpak (https://flatpak.org/) package. The patch can be removed, when the pull request #145 was merged.

### CODE REVIEW

**Comment by chipmuenk** [comment]
Thanks for creating the PR! I haven't created flatpaks myself yet and have absolutely no experience, so I have to rely on your input. 

If I understand this right, a flatpak would allow the user to install pyfda without needing a full blown python installation (a separate one from the OS python version)? This sounds great, my only pain is that I don't know how to maintain the flatpack config / make files when releasing new versions of pyfda. Could you give me some more info on the steps required? Are usually only the config /make files (that you committed) distributed and all the required files are automatically fetched during install or are BLOBs being distributed?

**Comment by Murmele** [comment]
As I know, python is already included in the platform used by the program (2,3,4th line). I didn't find out which python version is included in this version, so I assumed 3.5 and this was correct (have to find out where do I find this information). At the moment the master branch is used to create the package, but if needed for a specific version of pyfda ( maybe to publish on flathub it's better to set the version) 
add the tag property to the source
`{
					"type": "git",
					"url": "https://github.com/chipmuenk/pyFDA.git"
},`

`{
					"type": "git",
                                        "tag": "v0.1.5",
					"url": "https://github.com/chipmuenk/pyFDA.git"
},`

To install the package from the manifest I will give you the commands when I'm at home. I'm relatively new with flatpak packaging but as I know there exist also the possibility to distribute the finish compiled program. I will check this out and also the possibility to push the program to the flathub repository to find the programs in the software centers like "gnome software" or so.

Like you see in the manifest (the json file) there are many python libraries included. If you need a new library just add it to the manifest like the others. If a new version if a library is needed, the url to the new package, the name of the new package in the python command above and the sha256 checksum must be changed.

**Comment by Murmele** [comment]
I saw that I gave network access to the program. Does the program need it? Otherwise I remove this option.

**Comment by chipmuenk** [comment]
Thanx once more for the detailed explanation! The process seems to be a bit similar to pip packaging. I also found

https://www.loganasherjones.com/2018/05/using-flatpak-with-python/

which gives a nice foundation.

No, currently pyfda doesn't need network access.

I plan to release version 0.2 of pyfda next month, I'll merge your PR's before that. Do I need to merge both? I didn't quite understand the part with the patch.

**Comment by Murmele** [comment]
If you merge the first one, the patch is anymore needed and I will remove it. I just added the patch, so it is standalone.
The desktop file is needed to store some information how to start the application without the command line, the place where the icon is stored and so on.
The appdata file is for the software centers. This file includes screenshots and several information about the application it self.

This are the comments I use to install the application
# building flatpak package into the repository "meinRepoPyFDA"
flatpak-builder --repo=meinRepoPyFDA --force-clean pyFDA com.github.chipmuenk.pyFDA.json
# adding repository
flatpak remote-add meinRepoPyFDA meinRepoPyFDA --no-gpg-verify
# installing application
flatpak install meinRepoPyFDA com.github.chipmuenk.pyFDA

Today I found a possibility to create a single package. I will add the commands here tomorrow.

**Comment by Murmele** [comment]
I deleted the patch, disabled network and updated to a newer kde platform, because version 5.10 is deprecated (So I had to change also some module version to use newer python)

**Comment by chipmuenk** [comment]
Scanning the diff for the json file, I noticed that a module kiwisolver is added to the flatpak which is not required by pyfda. Does Flatpak need this? On a first glance I missed the docutils module. While not strictly needed, it helps to nicely format text outputs.

In the XML file I noticed a section "description" - do you know what sort of information is usually found there? 

And one last thing: pyfda needs access to the file system for reading config files and exporting textfiles and graphics. Is this possible in Flatpak's sandboxed environment?

**Comment by chipmuenk** [comment]
@Murmele : Könntest Du mir eine PM schicken? Meine Mailadresse findest Du auf meiner GitHub Startseite. Ich würde gerne ein bisschen über Deployment, Test, Updates etc. diskutieren, aber das muss vielleicht nicht unbedingt hier sein.

**Comment by Murmele** [comment]
@chipmuenk: Hast du meine Email erhalten?

**Pull request merged**
